### ISSUE TITLE
ZoomX/Y/Z tween as mods bug?

### ISSUE THREAD

**Issue by Kirby5464** [XeroOl/notitg-xgml#2]
Apperently trying to ease zoom mods just makes it ease from 0 as well and pretty sure it should be ease from 100 instead tbh.
(Happens on both ease and ease_to.)

**Comment by XeroOl** [comment]
This bug is an issue that's pretty hard to change internally in the code. The way I'd recommend to work around it is to re-define the zoom mods as ease vars with a custom string builder.

```lua
ease_var('zoom', function(percent) return '*9e9 ' .. percent + 100 .. ' zoom' end)
ease_var('zoomx', function(percent) return '*9e9 ' .. percent + 100 .. ' zoomx' end)
ease_var('zoomy', function(percent) return '*9e9 ' .. percent + 100 .. ' zoomy' end)
ease_var('zoomz', function(percent) return '*9e9 ' .. percent + 100 .. ' zoomz' end)
```

This way, when it eases from `0`, it will behave as if it eases from `100`. Note that this is just redefining how the mod is turned into a string, so if you use `ease_to` with these ease var definitions, easing `zoom` to `0` is how you'd turn it off, instead of easing to `100`.

I don't think this is enough of an issue to rewrite the ease engine, but I'll re-open this ticket if you can find a use case where this workaround doesn't work.
